<#
.SYNOPSIS
  Phase 6: dump real as-built facts (read-only) to Markdown so docs/as-built.md is generated, not typed.

.DESCRIPTION
  Collects the facts that prove the identity lifecycle is actually in place - JML-managed accounts,
  the audit log summary, OU placement of leavers, group hygiene, the delegated rights, and the cloud
  control states - and writes them as Markdown into evidence\raw\ for sanitizing into the as-built
  document. Nothing is summarised by hand and nothing is estimated.

  Cloud sections are attempted only if the Microsoft.Graph modules are present and the operator is
  signed in; otherwise the script records "not queried" rather than leaving a blank that looks like a
  zero.

  Sanitize before pasting into docs/as-built.md: remove tenant ids, tenant domains, object ids and
  UPNs (AGENTS.md 4.6). The output file is written to evidence/raw/, which is git-ignored.

.EXAMPLE
  .\12-Get-IdentityAsBuilt.ps1
  Write evidence\raw\p02-as-built-facts.md

.EXAMPLE
  .\12-Get-IdentityAsBuilt.ps1 -Out 'C:\temp\p2-facts.md'
  Write the facts somewhere else for review.

.NOTES
  Read-only: no snapshot required. Run on DC01.
#>
[CmdletBinding()]
param(
    [string] $Out = "$PSScriptRoot\..\evidence\raw\p02-as-built-facts.md",
    [string] $Domain = 'ad.halden.internal'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ((Get-ADDomain).DNSRoot -ne $Domain) { throw 'Not the Halden lab domain. Aborting.' }

Import-Module ActiveDirectory -ErrorAction Stop
$root = (Get-ADDomain).DistinguishedName
$usersOu = "OU=Users,OU=Halden,$root"
$disabledOu = "OU=Disabled,$root"
$logDir = "$PSScriptRoot\..\logs"
$script:out = New-Object System.Collections.Generic.List[string]

function Md {
    param([string] $Title, $Object)
    $script:out.Add("")
    $script:out.Add("## $Title")
    $script:out.Add("")
    if ($null -eq $Object -or ($Object -is [string] -and -not $Object)) {
        $script:out.Add('_not queried in this run_')
        return
    }
    $script:out.Add('```')
    $script:out.Add((($Object | Out-String).Trim()))
    $script:out.Add('```')
}

$script:out.Add('# P2 identity lifecycle - as-built facts')
$script:out.Add("")
$script:out.Add("Collected: $((Get-Date).ToString('s')) on $(hostname) by $env:USERDOMAIN\$env:USERNAME")
$script:out.Add("")
$script:out.Add('> GENERATED by 12-Get-IdentityAsBuilt.ps1. Sanitize before publishing (AGENTS.md 4.6).')

# --- JML-managed accounts ----------------------------------------------------------------------
$managed = @(Get-ADUser -Filter { extensionAttribute1 -eq 'JML-Managed' } -SearchBase "OU=Halden,$root" `
    -SearchScope Subtree -Properties EmployeeID, Department, Title, MemberOf, Enabled, DistinguishedName)
Md 'JML-managed accounts' ($managed | Select-Object SamAccountName, EmployeeID, Department, Title, Enabled,
    @{n='OU';e={ ($_.DistinguishedName -split ',OU=', 2)[1] }})

Md 'Managed account count by department' ($managed | Where-Object Enabled |
    Group-Object Department | Sort-Object Name | Select-Object Name, Count)

Md 'Managed accounts by OU' ($managed | Group-Object { ($_.DistinguishedName -split ',')[1] } |
    Sort-Object Name | Select-Object Name, Count)

Md 'Managed accounts with no role group but Domain Users' (
    $managed | Where-Object { $_.Enabled } | ForEach-Object {
        $groups = @($_.MemberOf | ForEach-Object { (Get-ADGroup $_).SamAccountName } | Where-Object { $_ -ne 'Domain Users' })
        if ($groups.Count -eq 0) { [pscustomobject] @{ Sam = $_.SamAccountName; EmployeeID = $_.EmployeeID } }
    })

# --- Leavers -----------------------------------------------------------------------------------
$leavers = @(Get-ADUser -Filter * -SearchBase $disabledOu -SearchScope OneLevel -Properties Description, WhenChanged)
Md 'Accounts in OU=Disabled' ($leavers | Select-Object SamAccountName, @{n='Description';e={$_.Description}},
    @{n='LastChanged';e={$_.WhenChanged.ToString('yyyy-MM-dd')}})

$snapshots = @(Get-ChildItem -Path (Join-Path $logDir 'leavers') -Filter '*.json' -ErrorAction SilentlyContinue)
Md 'Leaver group snapshots captured' ($snapshots | Select-Object Name, @{n='Captured';e={$_.LastWriteTime.ToString('yyyy-MM-dd HH:mm')}})

# --- Audit log ---------------------------------------------------------------------------------
$auditPath = Join-Path $logDir 'jml-audit.csv'
if (Test-Path $auditPath) {
    $audit = @(Import-Csv $auditPath)
    Md 'Audit log actions by type' ($audit | Group-Object Action | Sort-Object Name | Select-Object Name, Count)
    Md 'Audit log - most recent 10 entries' ($audit | Select-Object -Last 10 Timestamp, Action, Target, Operator)
} else {
    Md 'Audit log actions by type' $null
}

# --- Delegation --------------------------------------------------------------------------------
$gmsa = Get-ADServiceAccount -Filter "Name -eq 'gmsa-jml'" -Properties PrincipalsAllowedToRetrieveManagedPassword -ErrorAction SilentlyContinue
if ($gmsa) {
    Md 'gMSA identity for the engine' ([pscustomobject]@{
        Name = $gmsa.Name
        Enabled = $gmsa.Enabled
        MemberOfDomainAdmins = @(Get-ADGroupMember 'Domain Admins' -Recursive | Where-Object SamAccountName -like '*gmsa-jml*').Count -gt 0
        PrincipalsAllowedToRetrievePassword = ($gmsa.PrincipalsAllowedToRetrieveManagedPassword.Name -join ', ')
    })
} else {
    Md 'gMSA identity for the engine' $null
}

# --- Cloud controls (only if the Graph session is available) -------------------------------------
$cloudQueried = $false
if (Get-Module -ListAvailable -Name Microsoft.Graph.Identity.SignIns) {
    try {
        Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
        if (Get-MgContext) {
            Import-Module Microsoft.Graph.Identity.SignIns -ErrorAction Stop
            $policies = @(Get-MgIdentityConditionalAccessPolicy)
            Md 'Conditional Access policies' ($policies | Select-Object DisplayName, State, Id)
            $cloudQueried = $true
        }
    } catch {
        Write-Warning "Cloud query failed: $($_.Exception.Message)"
    }
}
if (-not $cloudQueried) {
    Md 'Conditional Access policies' 'not queried in this run (no Graph session; run Connect-MgGraph first if you need this section)'
}

New-Item -ItemType Directory -Force -Path (Split-Path $Out) | Out-Null
$script:out | Set-Content -Path $Out -Encoding UTF8
Write-Host "Wrote $Out" -ForegroundColor Cyan
Write-Host 'This file is in evidence/raw/ (git-ignored). Sanitize it before pasting anything into docs/as-built.md.' -ForegroundColor DarkYellow
