#!/usr/bin/env bash
# P6 - Phase 5/6: validate 802.1X Wi-Fi (EAP-TLS) against NPS without an access point.
#
# WHAT IT PROVES: that the RADIUS and certificate path actually works - NPS accepts a device that
# presents a certificate issued by the Halden CA, and rejects one that does not. eapol_test stands
# in for the access point, so this can be done before any AP hardware exists (plan Phase 5, step 6).
#
# WHAT IT DOES NOT PROVE: that the real access point is configured correctly, whether as a
# supplicant or as a NAS, and whether the real SSID is broadcast. That still needs the AP or a
# recorded manual test - be honest about which of the two you have.
#
# HOST: LNX01 (a Halden lab host, AD-joined). Snapshot not required (read-only test).
# MODE A / R1: this talks only to the lab RADIUS server on the SERVERS subnet.
#
# SECRETS: the RADIUS shared secret is read from an environment variable or prompted for. It is
# never written to a file and never passed as a literal on the command line in anything committed.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
PKI_DIR="/etc/halden-lab/pki"
CONF="$PKI_DIR/p06-wifi-eapol.conf"

usage() {
  cat <<'EOF'
Usage: 10-Test-EapTls.sh --server RADIUS_IP [--ca FILE] [--cert FILE] [--key FILE] [--identity ID]

  --server    the NPS host (lab: 192.168.10.20 / fs01.ad.halden.internal)
  --ca        Halden root CA public certificate (default: /etc/halden-lab/pki/halden-root-ca.pem)
  --cert      client certificate for this device            (default: /etc/halden-lab/pki/lnx01-client.pem)
  --key       client private key for this device            (default: /etc/halden-lab/pki/lnx01-client.key)
  --identity  identity string (default: host/<fqdn>)

Environment:
  RADIUS_SHARED_SECRET   the shared secret from the password manager (prompted for if unset)

Result: eapol_test prints SUCCESS on an Access-Accept. Anything else is a failure to investigate.
EOF
}

SERVER=""; CA="$PKI_DIR/halden-root-ca.pem"; CERT="$PKI_DIR/lnx01-client.pem"; KEY="$PKI_DIR/lnx01-client.key"
IDENTITY="host/$(hostname -f 2>/dev/null || hostname)"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --server) SERVER="${2:-}"; shift 2 ;;
    --ca) CA="${2:-}"; shift 2 ;;
    --cert) CERT="${2:-}"; shift 2 ;;
    --key) KEY="${2:-}"; shift 2 ;;
    --identity) IDENTITY="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

# Halden lab guard (AGENTS.md Section 2).
[[ "$(hostname -d 2>/dev/null)" == "ad.halden.internal" || -f /etc/halden-lab ]] \
  || { echo "Not a Halden lab host. Aborting." >&2; exit 1; }

[[ -n "$SERVER" ]] || { echo "error: --server is required." >&2; usage; exit 2; }
[[ "$SERVER" =~ ^(192\.168\.[0-9]{1,3}\.[0-9]{1,3}|[a-z0-9.-]+\.ad\.halden\.internal)$ ]] \
  || { echo "error: refusing '$SERVER': only a lab address is allowed." >&2; exit 1; }

command -v eapol_test >/dev/null 2>&1 \
  || { echo "error: eapol_test not found. Install it: sudo apt-get install -y wpasupplicant" >&2; exit 1; }
for f in "$CA" "$CERT" "$KEY"; do
  [[ -r "$f" ]] || { echo "error: cannot read $f (certificate material is issued in the lab, not committed)." >&2; exit 1; }
done

if [[ -z "${RADIUS_SHARED_SECRET:-}" ]]; then
  read -r -s -p "RADIUS shared secret (from the password manager): " RADIUS_SHARED_SECRET
  echo
fi

write_config() {
  mkdir -p "$PKI_DIR"
  umask 077
  cat > "$CONF" <<CONF
# Generated by 10-Test-EapTls.sh for this run. Not committed, no secrets are stored in the repo.
network={
    ssid="Halden-Corp"
    key_mgmt=WPA-EAP
    eap=TLS
    identity="$IDENTITY"
    ca_cert="$CA"
    client_cert="$CERT"
    private_key="$KEY"
}
CONF
}

run_test() {
  echo "eapol_test -> RADIUS $SERVER as $IDENTITY"
  echo "(this exercises the NPS policy 'Wi-Fi-Corp': EAP-TLS, certificate issued by the Halden CA)"
  local out
  out="$(eapol_test -c "$CONF" -a "$SERVER" -s "$RADIUS_SHARED_SECRET" 2>&1 || true)"
  printf '%s\n' "$out" | grep -E 'SUCCESS|FAILURE|Access-(Accept|Reject)|eapol_sm|TLS' || true
  if printf '%s' "$out" | grep -q 'SUCCESS'; then
    echo "RESULT: SUCCESS - record it in docs/as-built.md and evidence/public/ (as a text excerpt)."
    return 0
  fi
  echo "RESULT: not successful. Check, in order: NPS certificate validity, the NAS client entry and" >&2
  echo "        shared secret, the Wi-Fi-Corp policy conditions, and the NPS security event 6273." >&2
  return 1
}

echo "Preconditions to confirm before trusting a SUCCESS:"
echo "  - NPS (FS01) holds a valid Halden-RAS-IAS-Server certificate."
echo "  - This device holds a client certificate issued by the Halden CA (certutil/eapol_test will fail otherwise)."
echo "  - The RADIUS client entry for the access point exists on NPS."
echo
write_config
trap 'rm -f "$CONF"' EXIT
run_test
